### ISSUE TITLE
Installing cron in boot2docker-xhyve to fix clock drift

### ISSUE THREAD

**Issue by girvo** [ailispaw/boot2docker-xhyve#17]
From what I can see, there is no `cron` installed in `boot2docker-xhyve`, is this correct?

One interesting bug is that the clock drifts while the host machine is asleep; this can cause things like AWS APIs to fail within Docker.

An easy fix is to run `sudo ntpclient -s -h pool.ntp.org` in the `boot2docker` VM. Ideally I'd like to put this in a `crontab`, however without `cron` in the VM, I am rather at a loss!

Any ideas?

**Comment by ailispaw** [comment]
boot2docker/boot2docker has /usr/sbin/crond and /usr/bin/crontab.

```
docker@boot2docker~$ cat /var/spool/cron/crontabs/root
# restart ntpd to combat laptop sleep + VM pause
0 * * * * killall ntpd > /dev/null 2>&1; /etc/rc.d/ntpd
```

**Comment by ailispaw** [comment]
Or just `$ sudo reboot` would be fine.

**Comment by girvo** [comment]
Ah beautiful, I couldn't find the crontab for the life of me. Thanks!

**Comment by xez** [comment]
xhyve should take care of the clock drift during host sleep eventually.

**Comment by ailispaw** [comment]
@xez That would be great.

**Comment by girvo** [comment]
@ailispaw It seems that it is incorrect even using NTP?

![screenshot](https://i.imgur.com/cfGyIpk.png)

That's after a fresh boot of the VM. Any ideas?

**Comment by ailispaw** [comment]
@girvo What is your TimeZone?
It is UTC always in the VM by default.

**Comment by girvo** [comment]
@ailispaw Brisbane/Australia (UTC +10).

The main issue that this causes is breaking the AWS S3 API, as it whinges about clock drift being too large :(

**Comment by ailispaw** [comment]
@girvo 
What about the time after executing `sudo /usr/local/bin/ntpclient -s -h pool.ntp.org`?
Will it adjust the clock correctly?

**Comment by ailispaw** [comment]
Oh you have already mention it at the first comment. Sorry.

**Comment by ailispaw** [comment]
I think that you can replace ntpd with ntpclient in the crontab and set more frequently.

**Comment by ailispaw** [comment]
Or you can run the following command in the host after resume. I think this is the easiest way.

```
$ make ssh -- sudo /usr/local/bin/ntpclient -s -h pool.ntp.org
```

**Comment by ailispaw** [comment]
> That's after a fresh boot of the VM. Any ideas?

I have no idea... I've never seen that before.

**Comment by ailispaw** [comment]
@girvo BTW,

![](https://camo.githubusercontent.com/9daad339d586276a35da3079966d302125686064/68747470733a2f2f692e696d6775722e636f6d2f6366477949706b2e706e67)

Brisbane/Australia (UTC +10) Oct 9, 9:44am -> Oct. 8, 23:44pm UTC
is correct.

**Comment by ailispaw** [comment]
Is this related to https://github.com/boot2docker/boot2docker/issues/1082?
