### ISSUE TITLE
Minor README revisions

### ISSUE THREAD

**Issue by grahampugh** [ailispaw/boot2docker-xhyve#18]
1. `make run` demands a password. In case it isn't obvious, this is your sudo password, not 'docker'. 
2. When logging in, there is no password. Entering 'docker' as username logs you straight in.
3. The command 'docker info' must be run in the VM, but this isn't reflected in the description.

I'd like to see some description about how might go about sharing volumes, exposing ports etc.

**Comment by ailispaw** [comment]
@grahampugh That's a good idea!
Could you make a PR for it?
That would be very helpful for me, because I'm not a native English speaker.

**Comment by grahampugh** [comment]
Yes, sure. I'm just looking up about sharing volumes, exposing ports now.
Also, do you have plans to move to Docker Machine rather than boot2docker? Docker appear to be deprecating boot2docker according to https://docs.docker.com/installation/mac/

**Comment by ailispaw** [comment]
There are some projects for it and I have been watching for a while.
https://github.com/nathanleclaire/docker-machine-xhyve
https://github.com/zchee/docker-machine-xhyve

**Comment by ailispaw** [comment]
I prefer this simple way though. :p

**Comment by ailispaw** [comment]
And also I made https://github.com/ailispaw/docker-root-xhyve as an alternative for boot2docker.

**Comment by ailispaw** [comment]
Leave a comment

**Comment by ailispaw** [comment]
Oops.
