### ISSUE TITLE
uuid2ip blocks forever with 2 wired NICs

### ISSUE THREAD

**Issue by takada-s** [ailispaw/boot2docker-xhyve#2]
I'm using MBA with a thunderbolt display and another USB-NIC.
MacOS recognizes wireless one, thunderbolt one and USB one.
In this case, uuid2ip's `dispatch_semaphore_wait()` blocks forever.

Disconnecting either thunderbolt display or USB-NIC solves this problem.
Removing Network-service of thunderbolt display entry in system-config pane also solves.

in the pane, following does not work:
- USB-NIC
- Thunderbolt Display LAN
- WiFi

and following does work:
- USB-NIC
- WiFi

I'm suspecting that this caused in multi-NICs environment.
Currently I can boot and login coreos by disabling Thunderbolt Display LAN service.

**Comment by ailispaw** [comment]
Thank you for letting me know the issue.

I borrow most of the code from xhyve.
I'm wondering if xhyverun.sh itself works fine without uuid2ip (uuid2mac).

**Comment by takada-s** [comment]
for confirmation, uuid2ip works fine if only one wired-NIC recognized.
uuid2ip blocks forever if two wired-NICs recognized, and also xhyverun.sh blocks.

sorry for confusing you.

**Comment by ailispaw** [comment]
I understand that. Don't be sorry.

I mean,
after `make uuid2ip-clean` (without uuid2ip), I would like to know whether xhyverun.sh blocks or not.

**Comment by ailispaw** [comment]
Anyway it seems that vmnet_start_interface() in vmnet.framework won't call the handler function and we can do nothing except your workaround..

**Comment by takada-s** [comment]
Oops, I appended thunderbolt display LAN service again to reproduct the situation, but the problem doesnt happen...
As you say, even if this is a commonly problem, it is not a problem of boot2docker-xhyve's one.
Closing this issue and I'll report if I found more specific situations. thanks.

**Comment by ailispaw** [comment]
I have a thunderbolt port replicator with one ethernet port and a thunderbolt ethernet adopter.
I connect them to my MBA and then try to boot up xhyve.
It seems fine in my case.

**Comment by ailispaw** [comment]
@takada-s I see. Please re-open or open a new issue then. Thanks.
