### ISSUE TITLE
Add "make upgrade"

### ISSUE THREAD

**Issue by AlexanderWillner** [ailispaw/boot2docker-xhyve#24]
To migrate e.g. to the next boot2docker release.

**Comment by ailispaw** [comment]
Hi @AlexanderWillner ,
Thank you for opening this.

Currently we don't have a way to get the current version of the local boot2docker.iso without booting up.

I guess that `make upgrade` is going to do just `rm boot2docker.iso && make` after `git pull origin master`, or always download the latest boot2docker.iso and make again.
Is it good for you?
Do you want more intelligent upgrade? Or do you have any idea to do that?

**Comment by AlexanderWillner** [comment]
Hi, thanks for the answer. Yes, something like `rm boot2docker.iso` (and probably other files if needed) is what I'd have in mind. Just upgraded to version 1.9 manually I thought `make upgrade` would be more convenient.

**Comment by ailispaw** [comment]
I see. Thanks.
I will do that just like https://github.com/ailispaw/docker-root-xhyve.
