### ISSUE TITLE
Running a container on startup?

### ISSUE THREAD

**Issue by girvo** [ailispaw/boot2docker-xhyve#25]
Hey there,

I want to run `nginx-proxy` at startup, as combining it with `dnsmasq` allows easy defining of URLs for web containers running on arbitrary ports.

How and where do I need to change to add this, and have it persist?

**Comment by ailispaw** [comment]
Hi @girvo ,

That depends on boot2docker itself.
Please see this.
https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition

You can use `/var/lib/boot2docker/bootlocal.sh` and/or `/var/lib/boot2docker/bootsync.sh`.
