### ISSUE TITLE
How to increase the disk space?

### ISSUE THREAD

**Issue by bubenkoff** [ailispaw/boot2docker-xhyve#27]
I do lots of image builds and that leads to a boot2docker guest out of space
How do i increase it?

**Comment by ailispaw** [comment]
It will be similar to https://github.com/ailispaw/docker-root-xhyve/blob/master/contrib/resizehdd.md.
At the last part, you need `tce-load -w -i e2fsprogs` to install `resize2fs` after reboot.

**Comment by bubenkoff** [comment]
would be nice to have it (disk size) as a variable in the Makefile

**Comment by ailispaw** [comment]
It's not easy to do that in this repo.
I guess that https://github.com/nlf/dhyve and/or https://github.com/nlf/dlite are good for you.

**Comment by bubenkoff** [comment]
thanks a lot!
