### ISSUE TITLE
Is there a way to increase disk space?

### ISSUE THREAD

**Issue by fivetanley** [ailispaw/boot2docker-xhyve#5]
Hey there,

Great project. It made it super easy to get started with boot2docker and xhyve! Thanks for putting the work into it.

While working with docker-compose on a rails app, I use the "make a container for persisting database/gems" strategy. As a result, my host container (in this case boot2docker) needs a bit more space than the default. I'm not sure how to coordinate this, but I'm willing to learn if you have time to point me in the right direction.

Thanks!

**Comment by ailispaw** [comment]
Hi,
Do you need just bigger persistent disk instead of the default 3GB?

You can make your own persistent disk.
The instruction is https://github.com/ailispaw/boot2docker-xhyve/tree/master/contrib/makehdd .

**Comment by fivetanley** [comment]
Great, thanks!
